// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.query;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link QueryEHRResource#ehrQuery(QueryEHRResourceEhrQueryParams) ehrQuery()} method of the <code>QueryEHRResource</code>
 * class.
 */
public class QueryEHRResourceEhrQueryParams extends MethodParameterBase
{
    /**
     * Gets the value of the <code>excludeDeleted</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that have been marked as deleted in thereturned list, to any other value to include them, or omit the parameter to have the implementation choose (typically using its most efficient option). </i></p>
     *
     * @return The value of the <code>excludeDeleted</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getExcludeDeleted()
    {
        return getQueryArgument("excludeDeleted");
    }

    /**
     * Sets the <code>excludeDeleted</code> query parameter.
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that have been marked as deleted in thereturned list, to any other value to include them, or omit the parameter to have the implementation choose (typically using its most efficient option). </i></p>
     *
     *
     * @param value The new value for the <code>excludeDeleted</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setExcludeDeleted(final String value)
    {
        setQueryArgument("excludeDeleted", value);
    }

    /**
     * Gets the value of the <code>excludeEmpty</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that contain no locatables</i></p>
     *
     * @return The value of the <code>excludeEmpty</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getExcludeEmpty()
    {
        return getQueryArgument("excludeEmpty");
    }

    /**
     * Sets the <code>excludeEmpty</code> query parameter.
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that contain no locatables</i></p>
     *
     *
     * @param value The new value for the <code>excludeEmpty</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setExcludeEmpty(final String value)
    {
        setQueryArgument("excludeEmpty", value);
    }

    /**
     * Gets the value of the <code>systemID</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An OpenEHR HierObjectID value specifying a systemID to search. Specify multipletimes to search multiple systemIDs, or do not specify to search all systemIDs.</i></p>
     *
     * @return The value of the <code>systemID</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getSystemID()
    {
        return getQueryArgument("systemID");
    }

    /**
     * Sets the <code>systemID</code> query parameter.
     *
     * <p><b>Description:</b> <i>An OpenEHR HierObjectID value specifying a systemID to search. Specify multipletimes to search multiple systemIDs, or do not specify to search all systemIDs.</i></p>
     *
     *
     * @param value The new value for the <code>systemID</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setSystemID(final String value)
    {
        setQueryArgument("systemID", value);
    }

    /**
     * Gets the value of the <code>subject</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An OpenEHR UIDBasedID value specifying a subject constraint on the EHRStatusassociated with the EHR.</i></p>
     *
     * @return The value of the <code>subject</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getSubject()
    {
        return getQueryArgument("subject");
    }

    /**
     * Sets the <code>subject</code> query parameter.
     *
     * <p><b>Description:</b> <i>An OpenEHR UIDBasedID value specifying a subject constraint on the EHRStatusassociated with the EHR.</i></p>
     *
     *
     * @param value The new value for the <code>subject</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setSubject(final String value)
    {
        setQueryArgument("subject", value);
    }

    /**
     * Gets the value of the <code>createdBefore</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An ISO8601 DateTime value specifying a constraint on the maximum value of thetime the EHR was created.</i></p>
     *
     * @return The value of the <code>createdBefore</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getCreatedBefore()
    {
        return getQueryArgument("createdBefore");
    }

    /**
     * Sets the <code>createdBefore</code> query parameter.
     *
     * <p><b>Description:</b> <i>An ISO8601 DateTime value specifying a constraint on the maximum value of thetime the EHR was created.</i></p>
     *
     *
     * @param value The new value for the <code>createdBefore</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setCreatedBefore(final String value)
    {
        setQueryArgument("createdBefore", value);
    }

    /**
     * Gets the value of the <code>createdAfter</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An ISO8601 DateTime value specifying a constraint on the minimum value of thetime the EHR was created.</i></p>
     *
     * @return The value of the <code>createdAfter</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getCreatedAfter()
    {
        return getQueryArgument("createdAfter");
    }

    /**
     * Sets the <code>createdAfter</code> query parameter.
     *
     * <p><b>Description:</b> <i>An ISO8601 DateTime value specifying a constraint on the minimum value of thetime the EHR was created.</i></p>
     *
     *
     * @param value The new value for the <code>createdAfter</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setCreatedAfter(final String value)
    {
        setQueryArgument("createdAfter", value);
    }

}
