// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.query;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link XQueryLocatableResource#locatableXQuery(XQueryLocatableResourceLocatableXQueryParams) locatableXQuery()} method of the <code>XQueryLocatableResource</code>
 * class.
 */
public class XQueryLocatableResourceLocatableXQueryParams extends MethodParameterBase
{
    /**
     * Gets the value of the <code>q</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An XQuery, written to run against (a) collection(s) that contains openEHR XML data and toreturn a list of xml fragments that can be parsed as locatables</i></p>
     *
     * @return The value of the <code>q</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getQ()
    {
        return getQueryArgument("q");
    }

    /**
     * Sets the <code>q</code> query parameter.
     *
     * <p><b>Description:</b> <i>An XQuery, written to run against (a) collection(s) that contains openEHR XML data and toreturn a list of xml fragments that can be parsed as locatables</i></p>
     *
     * <b>This parameter is required and must be set before making a request!</b>
     *
     * @param value The new value for the <code>q</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setQ(final String value)
    {
        setQueryArgument("q", value);
    }

    /**
     * Gets the value of the <code>ehr</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>An OpenEHR HierObjectID value specifying an EHR to search. Specify multiple times to searchmultiple EHRs, or do not specify to search all EHRs. Note that the nature of combining XQuery and non-XQuery constraints may mean that the OR-ing of this constraint with the XQuery constraint may not be very efficient or performant, depending on the server storage implementation(s) in use.</i></p>
     *
     * @return The value of the <code>ehr</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getEhr()
    {
        return getQueryArgument("ehr");
    }

    /**
     * Sets the <code>ehr</code> query parameter.
     *
     * <p><b>Description:</b> <i>An OpenEHR HierObjectID value specifying an EHR to search. Specify multiple times to searchmultiple EHRs, or do not specify to search all EHRs. Note that the nature of combining XQuery and non-XQuery constraints may mean that the OR-ing of this constraint with the XQuery constraint may not be very efficient or performant, depending on the server storage implementation(s) in use.</i></p>
     *
     *
     * @param value The new value for the <code>ehr</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setEhr(final String value)
    {
        setQueryArgument("ehr", value);
    }

}
