package com.zorggemak.commons;

public enum MiddlewareErrors {
    // The error defines
    OK(0, "No errors"),

    REQ_TIMEOUT(1, "Request timeout"),
    AJAX_EXCEPTION(2, "Error generated by the Ajax request"),
    SERVER_EXCEPTION(3, "General java exception in Middleware server"),
    SOAP_EXCEPTION(4, "Soap EHR kernel exception"),

    NOTHING_FOUND(10, "Nothing found exception"),
    ARCHETYPE_ID_NOT_CORRECT(11, "Archetype id not correct exception"),
    ARCHETYPE_NOT_FOUND(12, "Archetype not found exception"),
    ARCHETYPE_EXISTS(13, "Archetype already exists exception"),
    OBJECT_NOT_FOUND(14, "Archetype object not found exception"),
    OBJECT_NOT_CORRECT(15, "Archetype object xml exception"),
    PATH_NOT_FOUND(16, "Archetype path not found exception"),
    ARCHETYPE_ID_NOT_SET(17, "Archetype id is not set"),
    INDEX_OUT_OF_RANGE(18, "Index out of range"),
    PARAMETERS_NOT_CORRECT(19, "Parameter(s) not correct"),
    OBJECT_NOT_UPDATABLE(20, "Archetype object is not updatable"),
    DATE_NOT_CORRECT(21, "Date(s) not correct"),
    USER_ID_REQUIRED(22, "X-On-Behalf-Of should contain USER_ID"),
    SYSTEM_ID_REQUIRED(23, "X-System-Id should contain SYSTEM_ID"),

    UNKNOWN(9999, "Unknown error");

    private final int errorcode;
    private final String errorstr;

    MiddlewareErrors(int code, String str) {
        this.errorcode = code;
        this.errorstr = str;
    }

    public int getErrorCode() {
        return errorcode;
    }

    public String getErrorString() {
        return errorstr;
    }

    @Override
    public String toString() {
        return (String.valueOf(errorcode));
    }

    public static String getHtmlTable() {
        MiddlewareErrors[] list = MiddlewareErrors.values();
        StringBuilder buf;

        buf = new StringBuilder();
        buf.append("<table border=\"1\">");
        for (int i = 0; i < list.length; i++) {
            buf.append("<tr><td>");
            buf.append(list[i].errorcode);
            buf.append("</td><td>");
            buf.append(list[i].errorstr);
            buf.append("</td></tr>");
        }
        buf.append("</table>");
        buf.append("\n");
        return (buf.toString());
    }

}
