// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.demo;

import org.restlet.data.Language;
import org.restlet.data.Preference;
import org.restlet.resource.ClientResource;
import org.restlet.resource.ResourceException;


import com.medvision360.lib.client.ClientResourceBase;
import com.medvision360.lib.client.ClientResourceConfig;
import com.medvision360.lib.client.ErrorDocument;
import com.medvision360.lib.common.exceptions.AnnotatedResourceException;
import com.medvision360.lib.common.exceptions.ApiException;

/**
    @apipath /demo

 */
public class MrDemoResource extends ClientResourceBase
{
    /**
     * Constructor.
     *
     * <p>This constructor can be used to create a new client for this resource.</p>
     *
     * @param config_ Configuration object containing the location of the server
     *   this resource sends requests to.
     */
    public MrDemoResource(
        final ClientResourceConfig config_
    )
    {
        super(config_, "/demo");
    }

    /**
       Demo resource.

Some extra text which shows up in swagger...



       <p>
       Use the {@link #getResult(String,MrDemoResourceGetResultParams)}
       method to pass additional query arguments.</p>

       @param demo A demo query parameter

       @apiqueryparam demo A demo query parameter.
[type=string,required,single,default=hello]



     */
    public com.medvision360.medrecord.api.demo.MrDemoResult getResult(
        final String demo
    ) throws
        com.medvision360.lib.api.MissingParameterException
    {
      return getResult(
        demo,
        null
      );
    }

    /**
       Demo resource.

Some extra text which shows up in swagger...



       @param queryParams_ The query parameters to be added to the request.
       @param demo A demo query parameter

       @apiqueryparam demo A demo query parameter.
[type=string,required,single,default=hello]


     */
    public com.medvision360.medrecord.api.demo.MrDemoResult getResult(
        final String demo,
        final MrDemoResourceGetResultParams queryParams_
    ) throws
        com.medvision360.lib.api.MissingParameterException
    {
        try
        {
            final ClientResource resource_ = getClientResource();
            if (queryParams_ != null)
            {
                queryParams_.applyTo(resource_);
            }

            resource_.addQueryParameter("demo", demo);
            final com.medvision360.medrecord.api.demo.MrDemoResource wrapped_ = resource_.wrap(com.medvision360.medrecord.api.demo.MrDemoResource.class);
            return wrapped_.getResult(
            );
        }
        catch(final ResourceException e_)
        {
            final ErrorDocument errorDocument_ = getErrorDocument();
            if (errorDocument_ != null)
            {
                switch(errorDocument_.getCode())
                {
                    case "MISSING_PARAMETER":
                        throw new com.medvision360.lib.api.MissingParameterException(errorDocument_.getArguments());
                }
            }
            throw e_;
        }
    }

}
