// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.archetype;

import org.restlet.data.Language;
import org.restlet.data.Preference;
import org.restlet.resource.ClientResource;
import org.restlet.resource.ResourceException;


import com.medvision360.lib.client.ClientResourceBase;
import com.medvision360.lib.client.ClientResourceConfig;
import com.medvision360.lib.client.ErrorDocument;
import com.medvision360.lib.common.exceptions.AnnotatedResourceException;
import com.medvision360.lib.common.exceptions.ApiException;

/**
    @apipath /archetype

 */
public class ArchetypeResource extends ClientResourceBase
{
    /**
     * Constructor.
     *
     * <p>This constructor can be used to create a new client for this resource.</p>
     *
     * @param config_ Configuration object containing the location of the server
     *   this resource sends requests to.
     */
    public ArchetypeResource(
        final ClientResourceConfig config_
    )
    {
        super(config_, "/archetype");
    }

    /**
       Demo resource.

Some extra text which shows up in swagger...



       <p>
       Use the {@link #getArchetype(String,ArchetypeResourceGetArchetypeParams)}
       method to pass additional query arguments.</p>

       @param id An OpenEHR ArchetypeID value

       @apiqueryparam id An OpenEHR ArchetypeID value.
[type=string,required,single,default=openEHR-EHR-OBSERVATION.blood_pressure.v1]



     */
    public org.restlet.representation.Representation getArchetype(
        final String id
    )     {
      return getArchetype(
        id,
        null
      );
    }

    /**
       Demo resource.

Some extra text which shows up in swagger...



       @param queryParams_ The query parameters to be added to the request.
       @param id An OpenEHR ArchetypeID value

       @apiqueryparam id An OpenEHR ArchetypeID value.
[type=string,required,single,default=openEHR-EHR-OBSERVATION.blood_pressure.v1]


     */
    public org.restlet.representation.Representation getArchetype(
        final String id,
        final ArchetypeResourceGetArchetypeParams queryParams_
    )     {
        try
        {
            final ClientResource resource_ = getClientResource();
            if (queryParams_ != null)
            {
                queryParams_.applyTo(resource_);
            }

            resource_.addQueryParameter("id", id);
            final com.medvision360.medrecord.api.archetype.ArchetypeResource wrapped_ = resource_.wrap(com.medvision360.medrecord.api.archetype.ArchetypeResource.class);
            return wrapped_.getArchetype(
            );
        }
        catch(final ResourceException e_)
        {
            throw e_;
        }
    }

}
