// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link EHRListResource#listEHRs(EHRListResourceListEHRsParams) listEHRs()} method of the <code>EHRListResource</code>
 * class.
 */
public class EHRListResourceListEHRsParams extends MethodParameterBase
{
    /**
     * Gets the value of the <code>excludeDeleted</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that have been marked as deleted in thereturned list, to any other value to include them, or omit the parameter to have the implementation choose (typically using its most efficient option).</i></p>
     *
     * @return The value of the <code>excludeDeleted</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getExcludeDeleted()
    {
        return getQueryArgument("excludeDeleted");
    }

    /**
     * Sets the <code>excludeDeleted</code> query parameter.
     *
     * <p><b>Description:</b> <i>Set to true to exclude EHRs that have been marked as deleted in thereturned list, to any other value to include them, or omit the parameter to have the implementation choose (typically using its most efficient option).</i></p>
     *
     *
     * @param value The new value for the <code>excludeDeleted</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setExcludeDeleted(final String value)
    {
        setQueryArgument("excludeDeleted", value);
    }

}
