// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link EHRListResource#listEHRs(EHRListResourceListEHRsParams) listEHRs()} method of the <code>EHRListResource</code>
 * class.
 */
public class EHRListResourceListEHRsParams extends MethodParameterBase
{
    /**
     * Gets the value of the <code>includeDeleted</code> query parameter.
     *
     * <p>The default value for the query parameter is <code>null</code>
     * meaning the parameter will not be included in the request.</p>
     *
     * <p><b>Description:</b> <i>Set to true to include EHRs that have been marked as deleted in thereturned list.</i></p>
     *
     * @return The value of the <code>includeDeleted</code> query parameter
     *   or <code>null</code> when the query parameter is not set.
     */
    public String getIncludeDeleted()
    {
        return getQueryArgument("includeDeleted");
    }

    /**
     * Sets the <code>includeDeleted</code> query parameter.
     *
     * <p><b>Description:</b> <i>Set to true to include EHRs that have been marked as deleted in thereturned list.</i></p>
     *
     *
     * @param value The new value for the <code>includeDeleted</code> query
     *   parameter. Use <code>null</code> (which also is the default value)
     *   to make sure the parameter is not added to the request.
     */
    public void setIncludeDeleted(final String value)
    {
        setQueryArgument("includeDeleted", value);
    }

}
