// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link EHRListResource#postEHR(org.restlet.representation.Representation, EHRListResourcePostEHRParams) postEHR()} method of the <code>EHRListResource</code>
 * class.
 */
public class EHRListResourcePostEHRParams extends MethodParameterBase
{
}
