// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link EHRResource#deleteEHR(EHRResourceDeleteEHRParams) deleteEHR()} method of the <code>EHRResource</code>
 * class.
 */
public class EHRResourceDeleteEHRParams extends MethodParameterBase
{
}
