// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import java.util.ArrayList;
import java.util.List;

import org.restlet.resource.ClientResource;

import com.medvision360.lib.client.MethodParameterBase;

/**
 * Class for adding query parameters to the request.
 *
 * <p>This class holds the query parameters used when making requests using the
 * {@link EHRUndeleteResource#undeleteEHR(EHRUndeleteResourceUndeleteEHRParams) undeleteEHR()} method of the <code>EHRUndeleteResource</code>
 * class.
 */
public class EHRUndeleteResourceUndeleteEHRParams extends MethodParameterBase
{
}
