// WARNING, THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT MODIFY !

package com.medvision360.medrecord.client.ehr;

import org.restlet.data.Language;
import org.restlet.data.Preference;
import org.restlet.resource.ClientResource;
import org.restlet.resource.ResourceException;


import com.medvision360.lib.client.ClientResourceBase;
import com.medvision360.lib.client.ClientResourceConfig;
import com.medvision360.lib.client.ErrorDocument;
import com.medvision360.lib.common.exceptions.AnnotatedResourceException;
import com.medvision360.lib.common.exceptions.ApiException;

/**
    @apipath /ehr/{id}/undelete
 @apipathparam id An OpenEHR HierObjectID value identifying an EHR.
   [type=string,required,single,default=71350448-25BA-4395-B354-19B9CA9D5096]

 */
public class EHRUndeleteResource extends ClientResourceBase
{
    /**
     * Constructor.
     *
     * <p>This constructor can be used to create a new client for this resource.</p>
     *
     * @param config_ Configuration object containing the location of the server
     *   this resource sends requests to.
     * @param id An OpenEHR HierObjectID value identifying an EHR
     */
    public EHRUndeleteResource(
        final ClientResourceConfig config_,
        final String id
    )
    {
        super(config_, "/ehr/" + id + "/undelete");
    }

    /**
       Undelete EHR resource.

Restores an existing EHR that has been deleted. Basically this removes the 'deleted' flag from the EHR record
that was put there by a previous <code>DELETE /ehr/{id}</code>.



       <p>
       Use the {@link #undeleteEHR(EHRUndeleteResourceUndeleteEHRParams)}
       method to pass additional query arguments.</p>


       

     */
    public void undeleteEHR(
    ) throws
        com.medvision360.medrecord.api.exceptions.NotFoundException,
        com.medvision360.medrecord.api.exceptions.ClientParseException,
        com.medvision360.medrecord.api.exceptions.RecordException,
        com.medvision360.medrecord.api.exceptions.IORecordException
    {
      undeleteEHR(
        null
      );
    }

    /**
       Undelete EHR resource.

Restores an existing EHR that has been deleted. Basically this removes the 'deleted' flag from the EHR record
that was put there by a previous <code>DELETE /ehr/{id}</code>.



       @param queryParams_ The query parameters to be added to the request.

       
     */
    public void undeleteEHR(
        final EHRUndeleteResourceUndeleteEHRParams queryParams_
    ) throws
        com.medvision360.medrecord.api.exceptions.NotFoundException,
        com.medvision360.medrecord.api.exceptions.ClientParseException,
        com.medvision360.medrecord.api.exceptions.RecordException,
        com.medvision360.medrecord.api.exceptions.IORecordException
    {
        try
        {
            final ClientResource resource_ = getClientResource();
            if (queryParams_ != null)
            {
                queryParams_.applyTo(resource_);
            }

            final com.medvision360.medrecord.api.ehr.EHRUndeleteResource wrapped_ = resource_.wrap(com.medvision360.medrecord.api.ehr.EHRUndeleteResource.class);
            wrapped_.undeleteEHR(
            );
        }
        catch(final ResourceException e_)
        {
            final ErrorDocument errorDocument_ = getErrorDocument();
            if (errorDocument_ != null)
            {
                switch(errorDocument_.getCode())
                {
                    case "NOT_FOUND_EXCEPTION":
                        throw new com.medvision360.medrecord.api.exceptions.NotFoundException(errorDocument_.getArguments());
                    case "CLIENT_PARSE_EXCEPTION":
                        throw new com.medvision360.medrecord.api.exceptions.ClientParseException(errorDocument_.getArguments());
                    case "RECORD_EXCEPTION":
                        throw new com.medvision360.medrecord.api.exceptions.RecordException(errorDocument_.getArguments());
                    case "IO_RECORD_EXCEPTION":
                        throw new com.medvision360.medrecord.api.exceptions.IORecordException(errorDocument_.getArguments());
                }
            }
            throw e_;
        }
    }

}
